services:
    fervo_enum.form_type.abstract:
        class: Fervo\EnumBundle\Form\EnumType
        abstract: true
        arguments:
            - ~ # enum class
            - ~ # type name

    fervo_enum.form_guesser:
        class: Fervo\EnumBundle\Form\EnumTypeGuesser
        public: false
        arguments:
            - @doctrine
            - %fervo_enum.doctrine_form_map%
        tags:
            - { name: form.type_guesser }

    fervo_enum.twig_extension:
        class: Fervo\EnumBundle\Twig\EnumExtension
        public: false
        arguments:
            - @translator
            - %fervo_enum.enum_map%
        tags:
            - { name: twig.extension }

    fervo_enum.jms_serializer.enum_handler:
        class: Fervo\EnumBundle\JMSSerializer\EnumHandler
        public: false
